program: main.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.01
  dropout_rate:
    min: 0.1
    max: 0.5
  batch_size:
    values: [16, 32, 64]
  num_epochs:
    values: [10, 20, 30]